# NOTE: heroku.ymlで使用するDockerfile
FROM ruby:3.4

RUN apt-get update -qq && \
  apt-get install -y build-essential default-libmysqlclient-dev nodejs vim

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app

# TODO: datadog使用する時にコメントアウト解除すること
# DDタグの設定
# ENV DD_SERVICE=app
# ENV DD_ENV=prod
# ENV DD_VERSION=1.0
